apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app
  namespace: argocd
spec:
  project: default

  source:
    path: demo-app
    repoURL: "https://github.com/trongitnlu/demo-infra.git"
    targetRevision: HEAD
  destination:
    name: ""
    namespace: demo-app
    server: "https://kubernetes.default.svc"

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
