apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: argocd
  labels:
    app: demo-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-app
          image: registry.khalinh.live/test-nextjs
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app-lb
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: demo-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-localhost
spec:
  ingressClassName: nginx
  rules:
    - host: demo-app.khalinh.live
      http:
        paths:
          - backend:
              service:
                name: demo-app-lb
                port:
                  number: 3000
            path: /
            pathType: Prefix
